#!/bin/bash
#SBATCH --job-name=aneu_eval
#SBATCH --output=/users/strt0792/MSc_Project/aneurysm_project/logs/eval_%j.log
#SBATCH --error=/users/strt0792/MSc_Project/aneurysm_project/logs/eval_%j.err
#SBATCH --time=02:00:00
#SBATCH --mem=32G
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu

module load miniforge/24.7.1
source activate aneuseg

BASE="/users/strt0792/MSc_Project/aneurysm_project"

echo "Job started : $(date)"
echo "Node        : $SLURMD_NODENAME"

python "$BASE/scripts/evaluate.py" \
    --processed_dir          "$BASE/data/processed" \
    --recon_dir              "$BASE/models/reconstruction" \
    --ae_ckpt                "$BASE/models/autoencoder/best_model.pt" \
    --out_dir                "$BASE/results" \
    --n_sensitivity_shapes   20

echo "Job finished : $(date)"
