#!/bin/bash
#SBATCH --job-name=aneu_preprocess_sdf
#SBATCH --output=/users/strt0792/MSc_Project/aneurysm_project/logs/preprocess_sdf_%j.log
#SBATCH --error=/users/strt0792/MSc_Project/aneurysm_project/logs/preprocess_sdf_%j.err
#SBATCH --time=06:00:00
#SBATCH --mem=32G
#SBATCH --cpus-per-task=8
#SBATCH --partition=nodes

module load miniforge/24.7.1
source activate aneuseg

BASE="/users/strt0792/MSc_Project/aneurysm_project"

echo "Job started  : $(date)"
echo "Node         : $SLURMD_NODENAME"

# SDF preprocessing — note the different output dir (processed_sdf)
python "$BASE/scripts/preprocess.py" \
    --data_root      "/users/strt0792/MSc_Project/6678442" \
    --out_dir        "$BASE/data/processed_sdf" \
    --n_surface      4096 \
    --n_space        4096 \
    --representation sdf

echo "Job finished : $(date)"