#!/bin/bash
#SBATCH --job-name=aneu_cvae
#SBATCH --output=/users/strt0792/MSc_Project/aneurysm_project/logs/cvae_%j.log
#SBATCH --error=/users/strt0792/MSc_Project/aneurysm_project/logs/cvae_%j.err
#SBATCH --time=06:00:00
#SBATCH --mem=32G
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu

module load miniforge/24.7.1
source activate aneuseg

BASE="/users/strt0792/MSc_Project/aneurysm_project"
echo "Job started : $(date)"
nvidia-smi --query-gpu=name --format=csv,noheader

python "$BASE/scripts/train_cvae.py" \
    --processed_dir "$BASE/data/processed_sdf" \
    --out_dir       "$BASE/models/cvae" \
    --n_epochs      800 \
    --batch_size    8 \
    --lr            5e-5 \
    --latent_dim    512 \
    --hidden_dim    512 \
    --n_freqs       3 \
    --clamp_dist    0.2 \
    --augment

echo "Job finished : $(date)"
