#!/bin/bash
#SBATCH --job-name=aneu_vae
#SBATCH --output=/users/strt0792/MSc_Project/aneurysm_project/logs/vae_%j.log
#SBATCH --error=/users/strt0792/MSc_Project/aneurysm_project/logs/vae_%j.err
#SBATCH --time=12:00:00
#SBATCH --mem=32G
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu

module load miniforge/24.7.1
source activate aneuseg

BASE="/users/strt0792/MSc_Project/aneurysm_project"

echo "Job started  : $(date)"
echo "Node         : $SLURMD_NODENAME"
nvidia-smi --query-gpu=name,memory.total --format=csv,noheader

python "$BASE/scripts/train_vae.py" \
    --processed_dir    "$BASE/data/processed_sdf" \
    --out_dir          "$BASE/models/vae" \
    --n_epochs         800 \
    --batch_size       8 \
    --lr               5e-5 \
    --latent_dim       512 \
    --hidden_dim       512 \
    --n_freqs          3 \
    --kl_weight        1e-5 \
    --kl_anneal_epochs 150 \
    --clamp_dist       0.2 \
    --free_bits        0.5 \
    --surface_weight   5.0 \
    --augment

echo "Job finished : $(date)"